# v7.0.4
[buildPlans.iosevka-nb]
family = "Iosevka NB"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-nb.variants]
inherits = "ss20"

[buildPlans.iosevka-nb.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
#capital-w = "straight"
capital-z = "curly-serifless-with-crossbar"
a = "double-storey-tailed"
d = "tailed-serifless"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "double-storey"
h = "tailed"
j = "flat-hook-serifed"
k = "cursive-serifless"
m = "tailed"
n = "tailed"
q = "tailed"
t = "flat-hook"
u = "tailed"
# looks too much like "u"
#v = "cursive-serifed"
w = "cursive"
x = "cursive"
y = "curly-turn"
z = "cursive"
long-s = "flat-hook-tailed"
lower-lambda = "curly-turn"
cyrl-capital-u = "curly-turn"
six = "straight-bar"
seven = "bend-crossbar"
eight = "two-circles"
nine = "straight-bar"
asterisk = "hex-high"
at = "fourfold"
percent = "rings-continuous-slash"
