# v15.5.2

[buildPlans.iosevka-nb]
family = "Iosevka NB"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-nb.variants]
inherits = "ss20"

[buildPlans.iosevka-nb.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
f = "flat-hook-crossbar-at-x-height"
g = "double-storey"
j = "flat-hook-serifed"
r = "hookless"
t = "flat-hook"
y = "curly-turn"
long-s = "flat-hook-tailed"
lower-lambda = "curly-turn"
cyrl-capital-u = "curly-turn"
six = "straight-bar"
seven = "bend-serifless"
eight = "two-circles"
nine = "straight-bar"
asterisk = "hex-high"
at = "fourfold"
percent = "rings-continuous-slash"
