# from https://stackoverflow.com/a/58468828
name: Update version
on:
  schedule:
    - cron: "0 2 * * *"
  push:
    paths:
      - "**.yml"
    tags-ignore:
      - 'release-*'

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CUSTOM_TOKEN }}
      - name: Set release version
        run: |
          VER=$(curl -sL https://api.github.com/repos/be5invis/iosevka/releases/latest | jq -r ".tag_name")
          sed -i "1s/.*/# $VER/" private-build-plans.toml
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'NBonaparte'
          git config --global user.email 'nbonaparte@users.noreply.github.com'
          git commit -am "New Iosevka version"
          git push

